name: leapcontrol

channels:
  - defaults
  - speleo3
  - conda-forge

dependencies:
  - python=3.6
  - numpy
  - leap-motion-python
  - kivy
  - scipy
  - cython

  - pip:
    - mido
    - python-rtmidi
    - ffpyplayer
    - hidapi
    - fluidsynth
